### ISSUE TITLE
Update JaCoCo to 0.8.7

### ISSUE THREAD

**Issue by raquezha** [NeoTech-Software/Android-Root-Coverage-Plugin#34]
I've encountered an issue 
```
Caused by: java.lang.IllegalStateException: Unexpected SMAP line: *S KotlinDebug
```

and it is related to [this reported issue](https://github.com/jacoco/jacoco/issues/1155)  

and fortunately for me it is now fixed today in version 0.8.7! We just to updated JaCoCo!

[JaCoCo 0.8.7 has been released](https://twitter.com/_godin_/status/1389728203342757891)
[JaCoCo Changelogs](https://www.jacoco.org/jacoco/trunk/doc/changes.html)

**Comment by Rolf-Smit** [comment]
Thanks for reporting this issue.

Please note that this Gradle Plugin does not enforce any JaCoCo version, it is just using the default JaCoCo version that is available or the version that is set by using:

```
    // Add to your build script (can be used after you apply the Jacoco plugin)

    jacoco {
        toolVersion = "0.8.7"
    }
```

Your pull-request doesn't affect the actual plugin, it is just changing the JaCoCo version that is used to test the plugin itself, are you aware of that? In other words the `IllegalStateException` that you are experiencing can be fixed without actually updating this plugin, just change the version using the `toolVersion` property.

**Comment by raquezha** [comment]
Hello @Rolf-Smit, thank you for your reply. I'm not aware of anything hahah I just started learning things few days ago found this library. where can I update the toolVersion?

**Comment by raquezha** [comment]
Can I ask a question? (not related to this)

when I run `./gradlew coverageReport` it's not creating to level build reports I'm using this on a multi-module project, i can see the generated report per build but not the consolidated report, how can I fix this problem? I guess I'm doing something wrong

**Comment by raquezha** [comment]
Oh my god what a noob error. I just follow your guide I didn't know there's a `./gradlew rootCoverageReport` I just did some digging. Anyway thanks for you response, I'm still new at code coverage and still learning a lot of things! thank you for this plugin! 

Have a nice day! ✨

**Comment by markchristopherng** [comment]
Hi, updated our Android project to 0.8.7 and we still get

**Comment by raquezha** [comment]
@markchristopherng I think you still have 0.8.6 dependency you're issue is related to this 
https://github.com/jacoco/jacoco/issues/1155#issuecomment-832642347

**Comment by markchristopherng** [comment]
Yeah i solved it by adding this build script.

configurations.all {
        resolutionStrategy {
            eachDependency { details ->
                if ('org.jacoco' == details.requested.group) {
                    details.useVersion "$versions.jacoco"
                }
            }
        }
    }

**Comment by Rolf-Smit** [comment]
@markchristopherng this plugin itself does not require any specific JaCoCo version, you can verify this by looking at the pom.xml file for this Plugin:

https://search.maven.org/artifact/nl.neotech.plugin/android-root-coverage-plugin/1.4.0/jar

Something else must be adding a dependency to that 0.8.6 version of JaCoCo. I could be mistaken, but maybe you can check that by running a dependency report.
