### ISSUE TITLE
rootCoverage configuration

### ISSUE THREAD

**Issue by wwwhackcom** [NeoTech-Software/Android-Root-Coverage-Plugin#72]
Hi, a quick question, how and where to put this **rootCoverage** in an Android gradle multiple-module project. 
Any chance you have an example code? Many thanks!

**Comment by Rolf-Smit** [comment]
There is not really an example, but if you go through the readme file the process should be really straight forward, just follow the exact steps outlined in the readme. The `rootCoverage` block goes into the root `/build.gradle` file.

If you still struggle, you can look at the project that is used for testing the plugin itself: https://github.com/NeoTech-Software/Android-Root-Coverage-Plugin/tree/master/plugin/src/test/test-fixtures/multi-module

Just look into the `/build.gradle` file which you find there.
