### ISSUE TITLE
Default configuration values

### ISSUE THREAD

**Issue by johnjohndoe** [NeoTech-Software/Android-Root-Coverage-Plugin#76]
Currently, the following configuration example can be found in the [README](https://github.com/NeoTech-Software/Android-Root-Coverage-Plugin/blob/d4a5cb47583bec6f5a1d36ce43200452fb09e80a/README.md#3-configuration):

``` groovy
rootCoverage {
   // The default build variant for every module
   buildVariant "debug"
   // Overrides the default build variant for specific modules.
   buildVariantOverrides ":moduleA" : "debugFlavourA", ":moduleB": "debugFlavourA"

   // Class & package exclude patterns
   excludes = ["**/some.package/**"]

   // Since 1.1 generateHtml is by default true
   generateCsv false
   generateHtml true
   generateXml false

   // Since 1.2: Same as executeTests except that this only affects the instrumented Android tests
   executeAndroidTests true

   // Since 1.2: Same as executeTests except that this only affects the unit tests
   executeUnitTests true

   // Since 1.2: When true include results from instrumented Android tests into the coverage report
   includeAndroidTestResults true

   // Since 1.2: When true include results from unit tests into the coverage report
   includeUnitTestResults true
   
   // Since 1.4: Sets jacoco.includeNoLocationClasses, so you don't have to. Helpful when using Robolectric
   // which usually requires this attribute to be true
   includeNoLocationClasses false
}
```

In order to understand which properties I need to apply to a given project I would love to see for each property which **default value** it comes with, like it is pointed out for `generateHtml`.

**Comment by Rolf-Smit** [comment]
This is a very good suggestion and something that would be helpful to many people. I'm going to work on this.

**Comment by lesbiangunshow** [comment]
just wanted to add, its unclear to me where this config block is actually supposed to go. maybe obvious to experts but im having to apply trial and error

**Comment by Rolf-Smit** [comment]
@lesbiangunshow this block should go in the `build.gradle` file at the root of your project (so not the one in the `app/` module).

Example: https://github.com/NeoTech-Software/Android-Root-Coverage-Plugin/blob/master/plugin/src/test/test-fixtures/multi-module/build.gradle

**Comment by Rolf-Smit** [comment]
Long time, but I created a wiki page with default values: https://github.com/NeoTech-Software/Android-Root-Coverage-Plugin/wiki/Configuration#options
