### ISSUE TITLE
rootCoveragereport doesn't build with configuration cache enabled

### ISSUE THREAD

**Issue by LegendaryZ** [NeoTech-Software/Android-Root-Coverage-Plugin#81]
191 problems were found reusing the configuration cache, 1 of which seems unique.
- Task `:rootCoverageReport` of type `org.gradle.testing.jacoco.tasks.JacocoReport`: cannot deserialize object of type 'org.gradle.api.Project' as these are not supported with the configuration cache.
  See https://docs.gradle.org/7.6/userguide/configuration_cache.html#config_cache:requirements:disallowed_types

**Comment by Rolf-Smit** [comment]
It seems that this plugin right now does not correctly support the Gradle configuration cache. I marked this as an enhancement for now.

**Comment by Rolf-Smit** [comment]
This will be available in release 1.8.0 (planned to be compatible with Android Gradle Plugin 8.3), right now this is only available as a bleeding edge [1.8.0-SNAPSHOT build](https://github.com/NeoTech-Software/Android-Root-Coverage-Plugin/wiki/How-to-use-SNAPSHOT-versions%3F).
