### ISSUE TITLE
rootCoverage is unresolved for kts gradle

### ISSUE THREAD

**Issue by amirraza** [NeoTech-Software/Android-Root-Coverage-Plugin#95]
I am trying to integrate in kotlin based project but unfortunately plugin is not showing up in gradle tasks.

How am I integrating?

//root project `build.gradle.kts`
```
plugins {
    alias(libs.plugins.androidApplication) apply false
    alias(libs.plugins.jetbrainsKotlinAndroid) apply false
    alias(libs.plugins.androidLibrary) apply false
    id("nl.neotech.plugin.rootcoverage") version "1.7.1" apply false
}
```
`settings.gradle.kts`
```
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url = uri("https://plugins.gradle.org/m2/") }
    }
}
```

AGP: 8.3.0
Gradle: 8.4
Kotlin: 1.9.0
Android Studio Iguana

Is there anything that I am missing?

**Comment by amirraza** [comment]
So, I managed to download plugin `nl.neotech.plugin:android-root-coverage-plugin:1.8.0-SNAPSHOT` and gradle tasks are now showing up but `rootCoverage` block is unresolved.

**Comment by tuan-le-skedulo** [comment]
can you try with Gradle 8.6?

**Comment by Rolf-Smit** [comment]
Stable release 1.8.0 is now available.

I'm closing this issue, at it seems to be caused due to user error. Please reopen if issues remain.
